# Stubs for ssh2.exceptions (Python 3)


class SSH2Error(Exception): ...
class AgentProtocolError(SSH2Error): ...
class BadSocketError(SSH2Error): ...
class BadUseError(SSH2Error): ...
class BufferTooSmallError(SSH2Error): ...
class UnknownError(SSH2Error): ...
class SocketSendError(SSH2Error): ...
class SocketRecvError(SSH2Error): ...
class SocketDisconnectError(SSH2Error): ...
class PublicKeyProtocolError(SSH2Error): ...
class ProtocolError(SSH2Error): ...
class OutOfBoundaryError(SSH2Error): ...
class MethodNoneError(SSH2Error): ...
class InvalidPollTypeError(SSH2Error): ...
class FileError(SSH2Error): ...
class InvalidRequestError(SSH2Error): ...

class AgentError(SSH2Error): ...
class AgentConnectionError(AgentError): ...
class AgentGetIdentityError(AgentError): ...
class AgentListIdentitiesError(AgentError): ...

class SessionError(SSH2Error): ...
class BannerRecvError(SessionError): ...
class BannerSendError(SessionError): ...
class SCPProtocolError(SessionError): ...
class RequestDeniedError(SessionError): ...
class MethodNotSupported(SessionError): ...
class CompressError(SessionError): ...
class DecryptError(SessionError): ...
class EncryptError(SessionError): ...
class HostkeyInitError(SessionError): ...
class HostkeySignError(SessionError): ...
class KeyExchangeError(SessionError): ...
class SessionHandshakeError(SessionError): ...
class SessionHostKeyError(SessionError): ...
class SessionStartupError(SessionError): ...
class SocketTimeout(SessionError): ...
class Timeout(SessionError): ...
class ZlibError(SessionError): ...

class AuthenticationError(SSH2Error): ...
class AgentAuthenticationError(AuthenticationError): ...
class PublickeyUnverifiedError(AuthenticationError): ...
class PasswordExpiredError(AuthenticationError): ...

class ChannelError(SSH2Error): ...
class ChannelClosedError(ChannelError): ...
class ChannelEOFSentError(ChannelError): ...
class ChannelFailure(ChannelError): ...
class ChannelOutOfOrderError(ChannelError): ...
class ChannelPacketExceeded(ChannelError): ...
class ChannelRequestDenied(ChannelError): ...
class ChannelUnknownError(ChannelError): ...
class ChannelWindowExceeded(ChannelError): ...

class KnownHostError(SSH2Error): ...
class KnownHostAddError(KnownHostError): ...
class KnownHostDeleteError(KnownHostError): ...
class KnownHostGetError(KnownHostError): ...
class KnownHostReadFileError(KnownHostError): ...
class KnownHostReadLineError(KnownHostError): ...
class KnownHostWriteFileError(KnownHostError): ...
class KnownHostWriteLineError(KnownHostError): ...

class KnownHostCheckError(KnownHostError): ...
class KnownHostCheckFailure(KnownHostCheckError): ...
class KnownHostCheckMisMatchError(KnownHostCheckError): ...
class KnownHostCheckNotFoundError(KnownHostCheckError): ...

class PublicKeyError(SSH2Error): ...
class PublicKeyInitError(PublicKeyError): ...

class SFTPError(SSH2Error): ...
class SFTPHandleError(SFTPError): ...
class SFTPProtocolError(SFTPError): ...

